root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/marionette ./cmd/marionette"
bin = "tmp/marionette"
full_bin = "MARIONETTE_ADDR=:8080 MARIONETTE_CONFIG=./marionette.json ./tmp/marionette"
include_ext = ["go"]
exclude_dir = ["tmp", "bin", "web", "internal/webui/dist"]
delay = 200

[log]
time = false
